
-- Registration of Stairs (Alphabetical order)
darkage.register_stairs("hades_darkage:basalt")
darkage.register_stairs("hades_darkage:basalt_brick")
darkage.register_stairs("hades_darkage:basalt_rubble")
darkage.register_stairs("hades_darkage:chalked_bricks")
darkage.register_stairs("hades_darkage:gneiss")
darkage.register_stairs("hades_darkage:gneiss_brick")
darkage.register_stairs("hades_darkage:gneiss_rubble")
darkage.register_stairs("hades_darkage:marble")
darkage.register_stairs("hades_darkage:marble_tile")
darkage.register_stairs("hades_darkage:old_tuff_bricks")
darkage.register_stairs("hades_darkage:ors")
darkage.register_stairs("hades_darkage:ors_brick")
darkage.register_stairs("hades_darkage:ors_rubble")
darkage.register_stairs("hades_darkage:rhyolitic_tuff")
darkage.register_stairs("hades_darkage:rhyolitic_tuff_bricks")
darkage.register_stairs("hades_darkage:schist")
darkage.register_stairs("hades_darkage:serpentine")
darkage.register_stairs("hades_darkage:shale")
darkage.register_stairs("hades_darkage:slate")
darkage.register_stairs("hades_darkage:slate_brick")
darkage.register_stairs("hades_darkage:slate_rubble")
darkage.register_stairs("hades_darkage:slate_tile")
darkage.register_stairs("hades_darkage:stone_brick")
darkage.register_stairs("hades_darkage:straw_bale")
darkage.register_stairs("hades_darkage:tuff")
darkage.register_stairs("hades_darkage:tuff_bricks")

